# Generated by Django 2.2 on 2019-05-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '教学培训'), (2, '教学促进'), (3, '教学技术'), (4, '青年教师助课'), (5, '其他')], default=5, verbose_name='培训类别')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmsftt_auth.Department', verbose_name='开设单位')),
            ],
            options={
                'verbose_name': '培训项目',
                'verbose_name_plural': '培训项目',
                'permissions': (('add_program', '允许添加培训项目'), ('view_program', '允许查看培训项目'), ('change_program', '允许修改培训项目'), ('delete_program', '允许删除培训项目')),
                'default_permissions': (),
            },
        ),
    ]
