# Generated by Django 2.1.5 on 2019-04-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '培训项目',
                'verbose_name_plural': '培训项目',
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='培训类别名称')),
            ],
            options={
                'verbose_name': '培训类别',
                'verbose_name_plural': '培训类别',
            },
        ),
        migrations.CreateModel(
            name='ProgramForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='培训形式名称')),
            ],
            options={
                'verbose_name': '培训形式',
                'verbose_name_plural': '培训形式',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training_program.ProgramCategory', verbose_name='培训类别'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmsftt_auth.Department', verbose_name='开设单位'),
        ),
        migrations.AddField(
            model_name='program',
            name='form',
            field=models.ManyToManyField(blank=True, to='training_program.ProgramForm', verbose_name='培训形式'),
        ),
    ]
