# Generated by Django 2.2 on 2019-04-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '教学培训'), (2, '教学促进'), (3, '教学技术'), (4, '青年教师助课'), (5, '其他')], default=5, verbose_name='培训类别'),
        ),
    ]
