# Generated by Django 2.1.5 on 2019-01-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_program', '0002_auto_20190113_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramCatgegory',
            new_name='ProgramCategory',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='catgegory',
            new_name='category',
        ),
    ]
