# Generated by Django 2.2 on 2019-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_program', '0002_auto_20190427_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramCategory',
        ),
        migrations.RemoveField(
            model_name='program',
            name='form',
        ),
        migrations.DeleteModel(
            name='ProgramForm',
        ),
    ]
