# Generated by Django 2.1.5 on 2019-01-21 06:16
from django.db import migrations
from django.conf import settings



def populate_initial_data(apps, _):  # pylint: disable=all
    '''This function populates necessary data for deployment.'''
    # Create system-robot user as required by NotificationService.


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmsftt_auth', '0001_initial'),
        ('infra', '0002_auto_20190424_2058'),
        ('training_program', '0001_initial'),
        ('training_event', '0001_initial'),
        ('training_record', '0001_initial'),
        ('training_review', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
