language: python
sudo: required
dist: xenial
python: 3.7

services: mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
  - export DJANGO_SETTINGS_MODULE=TMSFTT.settings_ci
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS TMSFTT character set UTF8;'

script:
  - python -m flake8
  - find . -maxdepth 1 -type d -not -path './.*' -not -path './mock_cas' -not -path './scripts' -not -path './htmlcov' -not -path '.' | xargs python -m pylint
  - python -m coverage run manage.py test --debug-mode
  - python -m coverage report --skip-covered
  - export DJANGO_SETTINGS_MODULE=TMSFTT.settings_dev; python manage.py migrate

notifications:
    email: false

after_success:
    coveralls
