language: python
sudo: required
dist: xenial
python: 3.7

services: mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=TMSFTT.settings_ci
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS TMSFTT character set UTF8;'

script: ./scripts/presubmit_tests.sh

notifications:
    email: false

after_success:
    coveralls
