language: python
sudo: required
dist: xenial
python: 3.7

services: mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=TMSFTT.settings_ci
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS TMSFTT character set UTF8;'

script:
  - flake8
  - pylint auth infra training_program training_record training_review TMSFTT
  - coverage run manage.py test -v 2 --debug-mode

notifications:
    email: false

after_success:
    coveralls
