# Generated by Django 2.2 on 2019-05-21 03:02

from django.db import migrations, models
import secure_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InSecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='insecure-files/%Y/%m/%d', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '不安全文件',
                'verbose_name_plural': '不安全文件',
                'default_permissions': (),
            },
            bases=(secure_file.models.FileFromPathMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='secure-files/%Y/%m/%d', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '安全文件',
                'verbose_name_plural': '安全文件',
                'permissions': (('download_file', '文件的下载权限'),),
                'default_permissions': (),
            },
            bases=(secure_file.models.FileFromPathMixin, models.Model),
        ),
    ]
