# Generated by Django 2.2 on 2019-04-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='generated-files/%Y/%m/%d', verbose_name='文件路径')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '受保护文件',
                'verbose_name_plural': '受保护文件',
                'permissions': (('download_file', '拥有院系其他成员生成文件的下载权限'),),
                'default_permissions': (),
            },
        ),
    ]
