# Generated by Django 2.2 on 2019-05-06 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secure_file.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secure_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securefile',
            options={'default_permissions': (), 'permissions': (('download_file', '拥有院系其他成员生成文件的下载权限'),), 'verbose_name': '安全文件', 'verbose_name_plural': '安全文件'},
        ),
        migrations.AlterField(
            model_name='securefile',
            name='path',
            field=models.FileField(upload_to='secure-files/%Y/%m/%d', verbose_name='文件路径'),
        ),
        migrations.CreateModel(
            name='InSecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='insecure-files/%Y/%m/%d', verbose_name='文件路径')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '不安全文件',
                'verbose_name_plural': '不安全文件',
                'default_permissions': (),
            },
            bases=(secure_file.models.FileFromPathMixin, models.Model),
        ),
    ]
