# Generated by Django 2.2 on 2019-05-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file', '0002_auto_20190521_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securefile',
            options={'default_permissions': (), 'permissions': (('view_securefile', '下载文件'),), 'verbose_name': '安全文件', 'verbose_name_plural': '安全文件'},
        ),
    ]
