# Generated by Django 2.2 on 2019-05-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewnote',
            options={'default_permissions': (), 'permissions': (('add_reviewnote', '允许添加培训记录审核提示'), ('view_reviewnote', '允许查看培训记录审核提示')), 'verbose_name': '培训记录审核提示', 'verbose_name_plural': '培训记录审核提示'},
        ),
    ]
