# Generated by Django 2.1.5 on 2019-04-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewnote',
            name='field_name',
        ),
    ]
