# Generated by Django 2.2 on 2019-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcoefficient',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '参与'), (1, '专家')], default=0, verbose_name='参与角色'),
        ),
    ]
