# Generated by Django 2.1.5 on 2019-04-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '参与教师'), (1, '主讲人'), (2, '评委')], default=0, verbose_name='参与角色')),
                ('coefficient', models.FloatField(default=0.0, verbose_name='角色系数')),
                ('hours_option', models.PositiveSmallIntegerField(choices=[(0, '正常计算'), (1, '向上取整'), (2, '向下取整'), (3, '四舍五入')], default=0, verbose_name='学时取整方式')),
                ('workload_option', models.PositiveSmallIntegerField(choices=[(0, '正常计算'), (1, '向上取整'), (2, '向下取整'), (3, '四舍五入')], default=0, verbose_name='工作量取整方式')),
                ('campus_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_event.CampusEvent', verbose_name='校内培训活动')),
                ('off_campus_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_event.OffCampusEvent', verbose_name='校外培训活动')),
            ],
            options={
                'verbose_name': '培训活动系数',
                'verbose_name_plural': '培训活动系数',
            },
        ),
    ]
