# Generated by Django 2.1.5 on 2019-02-21 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 10, 28, 30, 640885, tzinfo=utc), verbose_name='截止报名时间'),
            preserve_default=False,
        ),
    ]
