# Generated by Django 2.1.5 on 2019-01-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusevent',
            options={'verbose_name': '校内培训活动', 'verbose_name_plural': '校内培训活动'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '活动报名记录', 'verbose_name_plural': '活动报名记录'},
        ),
        migrations.AlterModelOptions(
            name='offcampusevent',
            options={'verbose_name': '校外培训活动', 'verbose_name_plural': '校外培训活动'},
        ),
    ]
