# Generated by Django 2.2 on 2019-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='是否已由校级管理员审核确认'),
        ),
    ]
