# Generated by Django 2.2 on 2019-05-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0002_auto_20190509_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_participated',
        ),
    ]
