# Generated by Django 2.2 on 2019-05-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0004_auto_20190526_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcoefficient',
            name='campus_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coefficients', to='training_event.CampusEvent', verbose_name='校内培训活动'),
        ),
        migrations.AlterField(
            model_name='eventcoefficient',
            name='off_campus_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coefficients', to='training_event.OffCampusEvent', verbose_name='校外培训活动'),
        ),
    ]
