# Generated by Django 2.1.4 on 2019-01-09 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infra.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
        ('training_program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('program_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目名称')),
                ('time', models.DateTimeField(verbose_name='参加时间')),
                ('location', models.CharField(max_length=64, verbose_name='参加地点')),
                ('num_hours', models.FloatField(verbose_name='参加学时')),
                ('num_participants', models.PositiveIntegerField(verbose_name='参加人数')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已提交'), (1, '院系管理员已审核'), (2, '学校管理员已审核')], default=0, verbose_name='当前状态')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training_program.Program', verbose_name='培训项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='参加用户')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
            },
        ),
        migrations.CreateModel(
            name='RecordAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(0, '培训内容'), (1, '培训总结'), (2, '培训反馈'), (3, '其他附件')], verbose_name='附件类型')),
                ('path', models.FileField(upload_to=infra.utils.CustomHashPath('record_attachments'), verbose_name='附件地址')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_record.Record', verbose_name='培训记录')),
            ],
            options={
                'verbose_name': '培训记录附件',
                'verbose_name_plural': '培训记录附件',
            },
        ),
        migrations.CreateModel(
            name='RecordContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('content_type', models.PositiveSmallIntegerField(choices=[(0, '培训内容'), (1, '培训总结'), (2, '培训反馈')], verbose_name='内容类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_record.Record', verbose_name='培训记录')),
            ],
            options={
                'verbose_name': '培训记录内容',
                'verbose_name_plural': '培训记录内容',
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('operationlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infra.OperationLog')),
                ('pre_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '已提交'), (1, '院系管理员已审核'), (2, '学校管理员已审核')], null=True, verbose_name='更改前状态')),
                ('post_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '已提交'), (1, '院系管理员已审核'), (2, '学校管理员已审核')], null=True, verbose_name='更改后状态')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='状态更改描述信息')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_record.Record', verbose_name='培训记录')),
            ],
            options={
                'verbose_name': '培训及路状态更改日志',
                'verbose_name_plural': '培训及路状态更改日志',
            },
            bases=('infra.operationlog',),
        ),
    ]
