# Generated by Django 2.1.5 on 2019-04-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusEventFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('feedback', models.TextField(verbose_name='反馈内容')),
            ],
            options={
                'verbose_name': '培训活动反馈',
                'verbose_name_plural': '培训活动反馈',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '未反馈'), (5, '已反馈')], default=1, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='post_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '未反馈'), (5, '已反馈')], null=True, verbose_name='更改后状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='pre_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '未反馈'), (5, '已反馈')], null=True, verbose_name='更改前状态'),
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='training_record.Record', verbose_name='培训记录'),
        ),
    ]
