# Generated by Django 2.1.5 on 2019-04-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordattachment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='training_record.Record', verbose_name='培训记录'),
        ),
        migrations.AlterField(
            model_name='recordcontent',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='training_record.Record', verbose_name='培训记录'),
        ),
    ]
