# Generated by Django 2.2 on 2019-04-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='campus_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='training_event.CampusEvent', verbose_name='校内培训活动'),
        ),
    ]
