# Generated by Django 2.1.5 on 2019-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '参与教师'), (1, '主讲人'), (2, '评委')], default=0, verbose_name='参与角色'),
        ),
    ]
