# Generated by Django 2.2 on 2019-05-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordattachment',
            options={'default_permissions': (), 'permissions': (('view_recordattachment', '允许查看培训记录附件'), ('delete_recordattachment', '允许删除培训记录附件')), 'verbose_name': '培训记录附件', 'verbose_name_plural': '培训记录附件'},
        ),
    ]
