# Generated by Django 2.1.5 on 2019-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0002_auto_20190223_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核')], default=1, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='attachment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '培训内容'), (1, '培训总结'), (2, '培训反馈'), (3, '其他附件')], default=4, verbose_name='附件类型'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='post_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核')], null=True, verbose_name='更改后状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='pre_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核')], null=True, verbose_name='更改前状态'),
        ),
    ]
