# Generated by Django 2.1.5 on 2019-04-19 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0002_auto_20190414_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuseventfeedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='content',
            field=models.CharField(default=datetime.datetime(2019, 4, 19, 2, 33, 21, 498596, tzinfo=utc), max_length=120, verbose_name='反馈内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campuseventfeedback',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='training_record.Record', verbose_name='培训记录'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '培训反馈待提交'), (5, '培训反馈已提交')], default=1, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='post_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '培训反馈待提交'), (5, '培训反馈已提交')], null=True, verbose_name='更改后状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='pre_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员已审核'), (3, '学校管理员已审核'), (4, '培训反馈待提交'), (5, '培训反馈已提交')], null=True, verbose_name='更改前状态'),
        ),
    ]
