# Generated by Django 2.2 on 2019-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0002_auto_20190428_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '已提交'), (2, '院系管理员审核通过'), (3, '学校管理员审核通过'), (4, '培训反馈待提交'), (5, '培训反馈已提交'), (6, '院系管理员审核不通过'), (7, '学校管理员审核不通过'), (8, '状态关闭')], default=1, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='post_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员审核通过'), (3, '学校管理员审核通过'), (4, '培训反馈待提交'), (5, '培训反馈已提交'), (6, '院系管理员审核不通过'), (7, '学校管理员审核不通过'), (8, '状态关闭')], null=True, verbose_name='更改后状态'),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='pre_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '已提交'), (2, '院系管理员审核通过'), (3, '学校管理员审核通过'), (4, '培训反馈待提交'), (5, '培训反馈已提交'), (6, '院系管理员审核不通过'), (7, '学校管理员审核不通过'), (8, '状态关闭')], null=True, verbose_name='更改前状态'),
        ),
    ]
