# Generated by Django 2.2 on 2019-05-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0003_auto_20190430_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuseventfeedback',
            options={'default_permissions': (), 'permissions': (('view_recordcontent', '允许查看培训活动反馈'), ('add_recordcontent', '允许增加培训活动反馈')), 'verbose_name': '培训活动反馈', 'verbose_name_plural': '培训活动反馈'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'default_permissions': (), 'permissions': (('add_record', '允许添加培训记录'), ('view_record', '允许查看培训记录'), ('change_record', '允许修改培训记录'), ('delete_record', '允许删除培训记录'), ('review_record', '允许审核培训记录')), 'verbose_name': '培训记录', 'verbose_name_plural': '培训记录'},
        ),
        migrations.AlterModelOptions(
            name='recordattachment',
            options={'default_permissions': (), 'permissions': (('view_recordattachment', '允许查看培训记录附件'),), 'verbose_name': '培训记录附件', 'verbose_name_plural': '培训记录附件'},
        ),
        migrations.AlterModelOptions(
            name='recordcontent',
            options={'default_permissions': (), 'permissions': (('view_recordcontent', '允许查看培训记录内容'),), 'verbose_name': '培训记录内容', 'verbose_name_plural': '培训记录内容'},
        ),
        migrations.AlterModelOptions(
            name='statuschangelog',
            options={'default_permissions': (), 'verbose_name': '培训记录状态更改日志', 'verbose_name_plural': '培训记录状态更改日志'},
        ),
    ]
