# Generated by Django 2.2 on 2019-06-12 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_event', '0005_auto_20190527_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_record', '0003_auto_20190612_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('user', 'campus_event', 'off_campus_event')},
        ),
    ]
