# Generated by Django 2.1.5 on 2019-04-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0002_record_role'),
        ('training_record', '0003_auto_20190419_1033'),
    ]

    operations = [
    ]
