# Generated by Django 2.2 on 2019-05-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0005_auto_20190515_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuseventfeedback',
            options={'default_permissions': (), 'permissions': (('add_campuseventfeedback', '允许增加培训活动反馈'),), 'verbose_name': '培训活动反馈', 'verbose_name_plural': '培训活动反馈'},
        ),
    ]
