# Generated by Django 2.2 on 2021-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0006_auto_20190709_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuseventfeedback',
            name='inspiring_less_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='启发不大原因'),
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='inspiring_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '有启发，帮助很大'), (1, '启发帮助较大'), (2, '启发帮助不大')], null=True, verbose_name='启发度'),
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='profit_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='其他收益'),
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='profits',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='获得收益'),
        ),
        migrations.AddField(
            model_name='campuseventfeedback',
            name='willingness_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '有启发，帮助很大'), (1, '启发帮助较大'), (2, '启发帮助不大')], null=True, verbose_name='意愿度'),
        ),
    ]
