# Generated by Django 2.2 on 2019-05-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0006_auto_20190517_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'default_permissions': (), 'permissions': (('add_record', '允许添加培训记录'), ('view_record', '允许查看培训记录'), ('change_record', '允许修改培训记录'), ('delete_record', '允许删除培训记录'), ('review_record', '允许审核培训记录'), ('batchadd_record', '允许批量增加培训记录')), 'verbose_name': '培训记录', 'verbose_name_plural': '培训记录'},
        ),
    ]
