# Generated by Django 2.2 on 2019-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.SmallIntegerField(choices=[(0, '按校内培训总时长排名'), (1, '按校外培训总时长排名'), (2, '按培训总时长排名')], verbose_name='排序方式')),
                ('ranking', models.PositiveIntegerField(verbose_name='排名')),
                ('value', models.FloatField(verbose_name='值')),
            ],
            options={
                'verbose_name': '排名',
                'verbose_name_plural': '排名',
                'default_permissions': (),
            },
        ),
    ]
