# Generated by Django 2.2 on 2019-05-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.SmallIntegerField(choices=[(0, '按培训学时排名')], verbose_name='排序方式')),
                ('ranking', models.IntegerField(verbose_name='排名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '排名',
                'verbose_name_plural': '排名',
                'default_permissions': (),
                'unique_together': {('user', 'ranking_type')},
            },
        ),
    ]
