# Generated by Django 2.2 on 2019-05-21 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
        ('data_warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tmsftt_auth.Department', verbose_name='排名范围'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['department', 'ranking_type'], name='data_wareho_departm_e58959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('user', 'department', 'ranking_type')},
        ),
    ]
