# Generated by Django 2.2 on 2019-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking_type',
            field=models.SmallIntegerField(choices=[(0, '按校内培训总时长排名'), (1, '按校外培训总时长排名'), (2, '按培训总时长排名')], verbose_name='排序方式'),
        ),
    ]
