# Generated by Django 2.2 on 2019-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0002_auto_20190510_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='value',
            field=models.FloatField(default=0, verbose_name='值'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.PositiveIntegerField(verbose_name='排名'),
        ),
    ]
