# Generated by Django 2.2 on 2019-05-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmsftt_auth', '0005_user_administrative_department'),
        ('data_warehouse', '0003_auto_20190510_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tmsftt_auth.Department', verbose_name='排名范围'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('user', 'department', 'ranking_type')},
        ),
    ]
