# Generated by Django 2.2 on 2019-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0004_auto_20190511_1517'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['department', 'ranking_type'], name='data_wareho_departm_e58959_idx'),
        ),
    ]
