# Generated by Django 2.1.5 on 2019-01-18 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='学部学院名')),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='管理员列表')),
            ],
            options={
                'verbose_name': '学部学院信息',
                'verbose_name_plural': '学部学院信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='年龄')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmsftt_auth.Department', verbose_name='学部学院')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帐户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
