# Generated by Django 2.1.5 on 2019-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwid', models.CharField(db_column='DWID', max_length=20, verbose_name='单位ID')),
                ('dwmc', models.CharField(blank=True, db_column='DWMC', max_length=100, null=True, verbose_name='单位名称')),
                ('dwfzr', models.CharField(blank=True, db_column='DWFZR', max_length=20, null=True, verbose_name='单位负责人')),
                ('dwjxfzr', models.CharField(blank=True, db_column='DWJXFRZ', max_length=20, null=True, verbose_name='单位教学负责人')),
                ('lsdw', models.CharField(blank=True, db_column='LSDW', max_length=20, null=True, verbose_name='隶属单位')),
                ('sfyx', models.CharField(blank=True, db_column='SFYX', max_length=1, null=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '单位基本信息',
                'verbose_name_plural': '单位基本信息',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TeacherInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgh', models.CharField(db_column='ZGH', max_length=20, verbose_name='职工号')),
                ('jsxm', models.CharField(blank=True, db_column='JSXM', max_length=100, null=True, verbose_name='教师姓名')),
                ('nl', models.CharField(blank=True, db_column='NL', max_length=10, null=True, verbose_name='年龄')),
                ('xb', models.CharField(blank=True, db_column='XB', max_length=10, null=True, verbose_name='性别')),
                ('xy', models.CharField(blank=True, db_column='XY', max_length=10, null=True, verbose_name='学院')),
                ('rxsj', models.CharField(blank=True, db_column='RXSJ', max_length=10, null=True, verbose_name='入校时间')),
                ('rzzt', models.CharField(blank=True, db_column='RZZT', max_length=40, null=True, verbose_name='任职状态')),
                ('xl', models.CharField(blank=True, db_column='XL', max_length=40, null=True, verbose_name='学历')),
                ('zyjszc', models.CharField(blank=True, db_column='ZYJSZC', max_length=40, null=True, verbose_name='专业技术职称')),
                ('rjlx', models.CharField(blank=True, db_column='RJLX', max_length=40, null=True, verbose_name='任教类型')),
            ],
            options={
                'verbose_name': '教师基本信息',
                'verbose_name_plural': '教师基本信息',
                'default_permissions': (),
            },
        ),
    ]
