# Generated by Django 2.2 on 2019-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 'tmsftt_auth_user_groups',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='grouppermission',
            options={'default_permissions': (), 'managed': False, 'verbose_name': '用户组权限', 'verbose_name_plural': '用户组权限'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'default_permissions': (), 'managed': False, 'verbose_name': '用户权限', 'verbose_name_plural': '用户权限'},
        ),
    ]
