# Generated by Django 2.1.5 on 2019-04-03 05:53

from django.db import migrations

from auth.models import Role


def populate_initial_data(apps, schema_editor):
    roles = [Role(type=role_type) for role_type, _ in Role.ROLE_CHOICES]
    Role.objects.bulk_create(roles)


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]