# Generated by Django 2.2 on 2019-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 'tmsftt_auth_user_groups',
                'permissions': (('add_usergroup', '允许添加用户权限'), ('view_usergroup', '允许查看用户权限'), ('change_usergroup', '允许修改用户权限'), ('delete_usergroup', '允许删除用户权限')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
