# Generated by Django 2.1.5 on 2019-04-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='education_backgroun',
            new_name='education_background',
        ),
    ]
