# Generated by Django 2.2 on 2019-06-06 02:26

import auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_delete_userpermission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.models.ActiveUserManager()),
            ],
        ),
    ]
