# Generated by Django 2.2 on 2019-05-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_auto_20190501_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_department', to='tmsftt_auth.Department', verbose_name='所属机构'),
        ),
    ]
