# Generated by Django 2.2 on 2019-05-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermission',
            options={'default_permissions': (), 'managed': False, 'verbose_name': '用户组权限', 'verbose_name_plural': '用户组权限'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'default_permissions': (), 'managed': False, 'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'default_permissions': (), 'managed': False, 'verbose_name': '用户权限', 'verbose_name_plural': '用户权限'},
        ),
    ]
