# Generated by Django 2.1.5 on 2019-04-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '身份', 'verbose_name_plural': '身份'},
        ),
    ]
