# Generated by Django 2.1.5 on 2019-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_auto_20190423_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='raw_user_id',
        ),
    ]
