# Generated by Django 2.1.5 on 2019-04-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0002_departmentinfomation_teacherinfomation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmentinfomation',
            table='TBL_DW_INFO',
        ),
        migrations.AlterModelTable(
            name='teacherinfomation',
            table='TBL_JB_INFO',
        ),
    ]
