# Generated by Django 2.2 on 2019-05-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0003_department_super_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(blank=True, choices=[('T1', '职能部处'), ('T2', '直附属单位'), ('T3', '学部院系'), ('T4', '其他'), ('T5', '职能部门及直附属单位'), ('T6', '书院'), ('T7', '学院'), ('T8', '其他机构')], max_length=2, null=True, verbose_name='单位类型'),
        ),
        migrations.AlterField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_departments', to='tmsftt_auth.Department', verbose_name='所属机构'),
        ),
    ]
