# Generated by Django 2.2 on 2019-06-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0003_auto_20190606_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinformation',
            name='sjh',
            field=models.CharField(blank=True, db_column='SJH', max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='yxdz',
            field=models.CharField(blank=True, db_column='YXDZ', max_length=50, null=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
