# Generated by Django 2.1.5 on 2019-04-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0003_remove_user_raw_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentinformation',
            options={'default_permissions': (), 'ordering': ['dwid'], 'verbose_name': '单位基本信息', 'verbose_name_plural': '单位基本信息'},
        ),
        migrations.AlterModelOptions(
            name='teacherinformation',
            options={'default_permissions': (), 'ordering': ['zgh'], 'verbose_name': '教师基本信息', 'verbose_name_plural': '教师基本信息'},
        ),
    ]
