# Generated by Django 2.1.5 on 2019-04-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0003_auto_20190420_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentInfomation',
            new_name='DepartmentInformation',
        ),
        migrations.RenameModel(
            old_name='TeacherInfomation',
            new_name='TeacherInformation',
        ),
    ]
