# Generated by Django 2.2 on 2019-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0004_auto_20190606_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinformation',
            name='nl',
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='bzhzt',
            field=models.CharField(blank=True, db_column='BZHZT', max_length=4, null=True, verbose_name='博士后在站状态'),
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='csrq',
            field=models.CharField(blank=True, db_column='CSRQ', max_length=10, null=True, verbose_name='出生日期'),
        ),
    ]
