# Generated by Django 2.2 on 2019-05-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0004_auto_20190509_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrative_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_users', to='tmsftt_auth.Department', verbose_name='所属行政单位'),
        ),
    ]
