# Generated by Django 2.2 on 2019-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0005_user_administrative_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinformation',
            name='dwlx',
            field=models.CharField(blank=True, db_column='DWLX', max_length=4, null=True, verbose_name='单位类型'),
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='sjh',
            field=models.CharField(blank=True, db_column='SJH', max_length=40, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='yxdz',
            field=models.CharField(blank=True, db_column='YXDZ', max_length=40, null=True, verbose_name='邮箱地址'),
        ),
    ]
