# Generated by Django 2.2 on 2019-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0006_auto_20190514_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='手机号'),
        ),
    ]
