# Generated by Django 2.2 on 2019-05-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0006_auto_20190514_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
