# Generated by Django 2.2 on 2019-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0007_auto_20190612_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdminInformation',
            fields=[
                ('zgh', models.CharField(db_column='ZGH', max_length=20, primary_key=True, serialize=False, verbose_name='职工号')),
                ('jsxm', models.CharField(blank=True, db_column='JSXM', max_length=100, null=True, verbose_name='教师姓名')),
                ('dwid', models.CharField(db_column='DWID', max_length=20, verbose_name='单位ID')),
                ('dwmc', models.CharField(blank=True, db_column='DWMC', max_length=100, null=True, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '学部管理人员基本信息',
                'verbose_name_plural': '学部管理人员基本信息',
                'db_table': 'TBL_XBGL_INFO',
                'ordering': ['dwid'],
                'default_permissions': (),
            },
        ),
    ]
