# Generated by Django 2.2 on 2019-05-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsftt_auth', '0007_auto_20190515_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': (), 'verbose_name': '院系', 'verbose_name_plural': '院系'},
        ),
    ]
