# Generated by Django 2.1.5 on 2019-01-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='操作来源IP')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'PATCH'), (4, 'DELETE'), (5, 'HEAD'), (6, 'OPTIONS'), (7, 'TRACE')], verbose_name='HTTP方法')),
                ('url', models.URLField(max_length=256, verbose_name='请求URL')),
                ('referrer', models.URLField(max_length=256, verbose_name='来源URL')),
                ('user_agent', models.CharField(max_length=256, verbose_name='用户代理标识')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
    ]
