# Generated by Django 2.2 on 2019-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'permissions': (('view_notification', '允许查看通知'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='操作来源IP')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'PATCH'), (4, 'DELETE'), (5, 'HEAD'), (6, 'OPTIONS'), (7, 'TRACE')], verbose_name='HTTP方法')),
                ('url', models.URLField(max_length=256, verbose_name='请求URL')),
                ('referrer', models.URLField(blank=True, max_length=256, verbose_name='来源URL')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='用户代理标识')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='响应状态码')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'default_permissions': (),
            },
        ),
    ]
