# Generated by Django 2.2 on 2019-04-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20190424_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='响应状态码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='referrer',
            field=models.URLField(blank=True, max_length=256, verbose_name='来源URL'),
        ),
    ]
