# Generated by Django 2.1.5 on 2019-04-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20190420_1438'),
        ('infra', '0002_auto_20190419_0946'),
    ]

    operations = [
    ]
