# Generated by Django 2.2 on 2019-04-25 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_auto_20190425_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='响应状态码'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, verbose_name='用户代理标识'),
        ),
    ]
