# Generated by Django 2.2 on 2019-05-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20190425_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'default_permissions': (), 'permissions': (('view_notification', '允许查看通知'),), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='operationlog',
            options={'default_permissions': (), 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
    ]
